export const COPY = {
  common: {
    appName: "Alokasi - Catat Keuangan",
    appDescription: "Catat transaksi, kelola dompet, dan pantau keuanganmu",
    defaultName: "Alokasi",
    home: "Beranda",
    analysis: "Analisis",
    profile: "Profilku",
    cancel: "Batal",
    save: "Simpan",
    close: "Tutup",
    delete: "Hapus",
    loading: "Memuat...",
    processing: "Memproses...",
    saving: "Menyimpan...",
    saved: "Perubahan tersimpan",
    error: "Ada yang belum berhasil. Coba lagi ya",
    connectionError: "Koneksi sedang bermasalah. Coba lagi sebentar lagi",
  },
  auth: {
    loginTitle: "Selamat datang kembali",
    loginSubtitle: "Masuk untuk lanjut mencatat keuanganmu",
    registerTitle: "Buat akunmu",
    registerSubtitle: "Mulai catat keuanganmu dengan lebih rapi",
    login: "Masuk",
    register: "Daftar",
    email: "Email",
    emailPlaceholder: "Email kamu",
    password: "Password",
    name: "Nama lengkap",
    namePlaceholder: "Nama lengkap",
    confirmPassword: "Konfirmasi password",
    newPassword: "Password baru",
    google: "Lanjutkan dengan Google",
    or: "atau",
    showPassword: "Lihat password",
    hidePassword: "Sembunyikan password",
    loading: "Memuat...",
    invalidEmail: "Format email belum benar",
    shortPassword: "Password minimal 6 karakter",
    nameRequired: "Nama lengkap perlu diisi",
    passwordMismatch: "Password belum sama. Periksa kembali",
    loginFailed: "Email atau password belum sesuai. Coba cek lagi ya",
    emailInUse: "Email sudah terdaftar. Masuk ke akunmu",
    emailMethodUnavailable: "Login dengan email belum tersedia. Coba lagi nanti",
    authError: "Ada yang belum berhasil. Periksa koneksi lalu coba lagi",
  },
  dashboard: {
    hello: "Halo,",
    defaultName: "Alokasi",
    totalBalance: "Total Saldo",
    live: "Live",
    balanceDescription: "Gabungan semua dompetmu, rapi di satu tempat",
    recordTransaction: "Catat Transaksi",
    expensesToday: "Total Pengeluaran",
    incomeToday: "Total Pemasukan",
    wallets: "Dompet & E-Wallet",
    manage: "Kelola",
    loadingWallets: "Memuat dompetmu...",
    noWallets: "Belum ada dompet. Tambahkan dompet pertamamu untuk mulai mencatat",
    addWallet: "Tambah Dompet",
    budgets: "Budget",
    savingsGoal: "Target Tabungan",
    add: "Tambah",
    noGoals: "Belum ada target tabungan. Tambahkan target pertamamu untuk mulai menabung",
    transactionHistory: "Riwayat Transaksi",
    all: "Semua",
    sevenDays: "7 hari",
    thirtyDays: "30 hari",
    date: "Tanggal",
    fromDate: "Dari tanggal",
    throughDate: "Sampai tanggal",
    noTransactionsToday: "Belum ada catatan hari ini. Yuk, mulai dari transaksi pertamamu ✨",
    noTransactions: "Belum ada transaksi. Catatanmu akan muncul di sini",
    noTransactionsInRange: "Tidak ada transaksi pada periode ini. Coba pilih tanggal lain",
    transactionCount: "transaksi",
    quickWallet: "Dompet",
    quickReport: "Laporan",
    startDate: "Dari tanggal",
    endDate: "Sampai tanggal",
    startDateAria: "Tanggal mulai riwayat",
    endDateAria: "Tanggal akhir riwayat",
    transfer: "Transfer saldo",
    transaction: "Transaksi",
    logout: "Keluar",
    logoutConfirm: "Keluar dari akunmu?",
    savingsDeposit: "Setor ke Target Tabungan",
    depositAmount: "Nominal setoran (Rp)",
    walletSource: "Sumber dompet",
    depositAmountError: "Nominal setoran harus lebih dari Rp 0",
    chooseWallet: "Pilih dompet sumber dana",
    saveDepositError: "Setoran belum berhasil. Periksa saldo dan coba lagi",
    processingDeposit: "Memproses setoran...",
    confirmDeposit: "Konfirmasi setoran",
    receiptScanFailed: "Struk belum terbaca jelas. Coba foto ulang dengan cahaya lebih terang",
    imageReadFailed: "Gambar belum dapat dibaca. Coba pilih file lain",
    invalidImage: "Format gambar belum sesuai. Pilih file gambar yang valid",
  },
  transaction: {
    title: "Catat Transaksi",
    subtitle: "Catat pengeluaran, pemasukan, atau transfer",
    expense: "Pengeluaran",
    income: "Pemasukan",
    transfer: "Transfer",
    amount: "Nominal (Rp)",
    sourceWallet: "Dari dompet",
    destinationWallet: "Ke dompet",
    loadingWallets: "Memuat dompet...",
    noWallets: "Belum ada dompet",
    addWalletFirst: "Tambahkan dompet dulu untuk mulai mencatat",
    anotherWalletNeeded: "Pilih dompet lain",
    category: "Kategori",
    otherCategory: "Lainnya",
    newCategory: "Nama kategori baru",
    deleteCategory: "Hapus kategori",
    deleteCategoryConfirm: "Hapus kategori \"{name}\" dari pilihan? Riwayat lama tetap tersimpan",
    note: "Catatan (opsional)",
    notePlaceholder: "Contoh: Makan siang",
    save: "Simpan transaksi",
    deleteConfirm: "Hapus transaksi ini? Tindakan ini tidak bisa dibatalkan",
  },
  receipt: {
    title: "Scan Struk",
    permission: "Izinkan akses kamera untuk scan struk",
    success: "Struk berhasil dibaca. Cek dulu sebelum disimpan",
    failed: "Struk belum terbaca jelas. Coba foto ulang dengan cahaya lebih terang",
    reading: "Membaca struk...",
    upload: "Scan struk",
    invalidFormat: "Format foto struk belum sesuai. Pilih gambar JPEG, PNG, atau WebP",
    totalMissing: "Total belum ditemukan. Pastikan foto struk terlihat jelas",
  },
  wallet: {
    title: "Dompet & E-Wallet",
    subtitle: "Kelola dompet dan rekeningmu",
    add: "Tambah dompet",
    addNew: "Tambah dompet baru",
    name: "Nama dompet",
    namePlaceholder: "Contoh: Rekening utama",
    type: "Jenis",
    bank: "Bank",
    ewallet: "E-wallet",
    cash: "Tunai",
    openingBalance: "Saldo awal (Rp)",
    labelColor: "Warna label",
    delete: "Hapus dompet",
  },
  goal: {
    title: "Target Tabungan",
    add: "Tambah target",
      subtitle: "Mulai menabung untuk tujuanmu",
    name: "Nama target",
    namePlaceholder: "Contoh: Dana liburan",
    amount: "Nominal target (Rp)",
    initialAmount: "Saldo terkumpul (opsional)",
    save: "Simpan target",
    target: "Target",
    collected: "Terkumpul",
    remaining: "Sisa",
    achieved: "Target tercapai! Kamu hebat 💖",
    completed: "Tercapai",
    deposit: "Setor ke target",
  },
  budget: {
    title: "Budget",
    add: "Atur budget",
      subtitle: "Atur batas pengeluaran per kategori",
    category: "Kategori pengeluaran",
    monthlyLimit: "Batas bulanan (Rp)",
    spent: "Terpakai",
    remaining: "Sisa",
    limit: "Batas",
    noBudget: "Belum ada budget. Atur batas pengeluaranmu supaya lebih terkontrol",
    exceeded: "Pengeluaranmu sudah melewati batas budget. Yuk, cek ulang",
    withinLimit: "Dalam batas",
    overLimit: "Melewati batas",
  },
  gamification: {
    firstTransaction: "Catat transaksi pertamamu hari ini",
    streak: "{count} hari berturut-turut! Kamu konsisten banget 💖",
    badge: "Badge {level}",
    pointsToNext: "{count} poin lagi menuju {level}",
    highestLevel: "Level tertinggi tercapai",
    points: "Poin",
    success: "Tercatat! Satu langkah lagi menuju target keuanganmu",
    savings: "Pengeluaranmu lebih hemat dari kemarin 🌸",
    reminder: "Sudah catat transaksi hari ini? Cuma butuh semenit ✨",
  },
  analysis: {
    title: "Analisis / Laporan",
    cashFlow: "Arus Kas Bulan Ini",
    income: "Pemasukan",
    expenses: "Pengeluaran",
    netBalance: "Selisih bersih",
    byCategory: "Pengeluaran per kategori",
    empty: "Laporan akan muncul setelah kamu mencatat beberapa transaksi",
    noExpenses: "Belum ada pengeluaran bulan ini. Catatanmu akan muncul di sini",
    insight: "Insight keuangan",
    requestInsight: "Minta saran",
    analyzing: "Menganalisis...",
    insightInitial: "Saran keuanganmu akan muncul di sini",
    insightEmpty: "Belum ada transaksi. Catat transaksi untuk melihat saran keuangan",
    insightError: "Saran belum tersedia. Coba lagi sebentar",
    reportEmpty: "Laporan akan muncul setelah kamu mencatat beberapa transaksi",
  },
  account: {
    title: "Profilku",
    subtitle: "Kelola profil dan akunmu",
    loading: "Memuat...",
    member: "Bergabung sejak",
    memberFallback: "Pengguna Alokasi",
    wallets: "Total dompet",
    transactions: "Total transaksi",
    active: "aktif",
    edit: "Edit Profil",
    editSubtitle: "Nama lengkap dan foto profil",
    notifications: "Notifikasi",
    notificationSubtitle: "Pengingat pencatatan dan budget",
    dailyReminder: "Pengingat catat transaksi harian",
    budgetReminder: "Peringatan batas budget",
    security: "Keamanan",
    securitySubtitle: "Atur password akunmu",
    editTitle: "Edit Profil",
    changePhoto: "Ubah foto profil",
    choosePhoto: "Pilih foto profil",
    saveChanges: "Simpan perubahan",
    profileSaved: "Perubahan tersimpan",
    profileError: "Profil belum berhasil diperbarui. Periksa koneksi lalu coba lagi",
    imageError: "Gambar belum dapat dibaca. Pilih file lain lalu coba lagi",
    securityTitle: "Ubah password",
    passwordSaved: "Password berhasil diperbarui",
    passwordError: "Password belum berhasil diperbarui. Masuk kembali lalu coba lagi",
    resetData: "Hapus semua data",
    resetSubtitle: "Hapus riwayat, dompet, budget, dan target tabungan",
    resetTitle: "Hapus data keuangan?",
    resetWarning: "Riwayat transaksi, dompet, budget, dan target tabungan akan dihapus dari akunmu. Tindakan ini tidak bisa dibatalkan",
    resetSuccess: "Data keuangan berhasil dihapus",
    resetError: "Data belum berhasil dihapus. Periksa koneksi lalu coba lagi",
    resetConfirm: "Hapus semua data",
    logout: "Keluar",
    logoutConfirm: "Keluar dari akunmu?",
  },
  export: {
    title: "Ekspor Laporan",
    subtitle: "Unduh laporan transaksi dan saldo dompetmu",
    csv: "Format CSV / Excel",
    csvDescription: "Untuk dibuka dan diolah di Excel",
    pdf: "Format PDF",
    pdfDescription: "Dokumen siap dibaca dan dicetak",
    download: "Unduh laporan ({format})",
    pdfTitle: "Laporan Keuangan - Alokasi",
    printedAt: "Dicetak pada:",
    transactionType: "Jenis",
    amount: "Nominal (Rp)",
    categoryNote: "Kategori / Catatan",
    date: "Tanggal",
    category: "Kategori",
    wallet: "Dompet",
    note: "Catatan",
  },
  errors: {
    connection: "Koneksi sedang bermasalah. Coba lagi sebentar lagi",
    general: "Ada yang belum berhasil. Coba lagi ya",
    notFound: "Halaman tidak ditemukan. Kembali ke Beranda",
    sessionExpired: "Sesimu sudah berakhir. Masuk lagi untuk melanjutkan",
    scan: "Struk belum terbaca jelas. Coba foto ulang dengan cahaya lebih terang",
    invalidEmail: "Format email belum benar",
    insufficientBalance: "Saldo dompet belum cukup untuk setoran ini. Periksa saldo lalu coba lagi",
  },
  categories: {
    food: "Makanan & Kopi",
    personal: "Perawatan diri & Hiburan",
    shopping: "Belanja & Kebutuhan",
    income: "Pemasukan",
    transport: "Transportasi",
    bills: "Tagihan",
    daily: "Kebutuhan Harian",
    other: "Kategori lainnya",
  },
} as const;

export function formatTanggalIndonesia(date: Date) {
  return date.toLocaleDateString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}